# Generated by Django 3.2.10 on 2021-12-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_journalier_activites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
