# Generated by Django 3.2.10 on 2021-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_journalier_activites', '0002_alter_projet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='collaborateurs',
            field=models.ManyToManyField(blank=True, to='reporting_journalier_activites.Collaborateur'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='stagiaireAttribue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
