# Generated by Django 3.2.10 on 2021-12-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_journalier_activites', '0003_auto_20211220_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outil', to='reporting_journalier_activites.tache'),
        ),
    ]
